### ISSUE TITLE
Missing keyboard shortcut for clicking the button

### ISSUE THREAD

**Issue by ydyote** [cawa-93/youtube-forward-timeline#10]
Hello,

I quickly slapped together (0 experience with extensions) the shortcut for chrome, but have no idea how it should integrate to this repo, because it is chrome specific.

So if you want to integrate it, this works, but the default shortcut seems to not work properly. I think its because it overlaps the chrome built in open new window shortcut.

Originally I wanted to make the shortcut "n" but that was not valid for this kind of setup, it would work if the shortcut would be implemented as it is in  https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en 

to try it out:
 1. install chrome
 2. in chrome://extensions/ turn on developer mode
 3. click "load unpacked" and navigate to a directory which has unpacked the zip which I included here
 4. go to chrome://extensions/shortcuts and ensure a shortcut is set (if it is not set, set it to something) 
![image](https://user-images.githubusercontent.com/54998537/144746095-959d070c-e8e0-4377-aaa8-5316d2f8e4e3.png)
 5. go to a youtube video with chapters, wait for the button to load and press keys for the shortcut, it should work without errors (it works for me in "Google Chrome: Version 96.0.4664.45 (Official Build) (64-bit)"

[DOWNLOAD.YouTube.next.chapter.button.zip](https://github.com/cawa-93/youtube-forward-timeline/files/7655822/DOWNLOAD.YouTube.next.chapter.button.zip)

have a nice day

**Comment by cawa-93** [comment]
I just tried in Edge and it seems works as expected
