### ISSUE TITLE
Doesn't seem to work on Firefox 100.0.2

### ISSUE THREAD

**Issue by xan2622** [cawa-93/youtube-forward-timeline#12]
Hi.

I can't get the add-on (version 1.0.6) to work on Firefox 100.0.2 (Windows 64 bits).
I don't see the ⏩ button.

![Capture d’écran 2022-05-21 153305](https://user-images.githubusercontent.com/1732773/169653986-0ce33278-0eca-4c2e-969e-3364fa5b29a4.jpg)

**Comment by cawa-93** [comment]
Hi there. I think this is a video problem. The extension works by analyzing the description of the video and looking for timecodes in it. Just like YouTube itself builds segments for the timeline. I don't see any segments in your screenshot. I assume that the video does not have timecodes, so it cannot be divided into sections.

**Comment by xan2622** [comment]
Good catch. 👍

I have retried with other videos (some that feature "chapters segments") and indeed, the add-on worked fine: 
Example: https://www.youtube.com/watch?v=5NY9lOgnpLA

Thank you for your help.

edit: Now that I am thinking about it, it was a bit silly to expect the add-on to work on a video without chapters.. 🤦‍♂️
