### ISSUE TITLE
Why is this not on chrome web store?

### ISSUE THREAD

**Issue by shahin365** [cawa-93/youtube-forward-timeline#13]
Hi,
Why is this extension not on the Chrome web store?

**Comment by cawa-93** [comment]
Because some time ago, Google ban my web-store account without any explanation 🤷🏻‍♂️

**Comment by cawa-93** [comment]
Now it is available in Chrome web store. 

https://chrome.google.com/webstore/detail/youtube-next-chapter-butt/dnhblfjgbcgeoiidbbhephfmhamfkeak
