### ISSUE TITLE
support for Logitech Crown wheel?

### ISSUE THREAD

**Issue by markusd1984** [cawa-93/youtube-forward-timeline#8]
Nice extension for Chrome, well done! So powerful! 

I'm wondering if this could possibly be used to create a plugin for the Logitech Crown/Wheel?

https://github.com/Logitech/logi_craft_sdk/blob/master/documentation/Craft_Crown_SDK.md

Appreciate any thoughts/help you can offer.

**Comment by cawa-93** [comment]
You can try 🤷‍♂️
