### ISSUE TITLE
Error loading extension in Chrome

### ISSUE THREAD

**Issue by markusd1984** [cawa-93/youtube-forward-timeline#9]
Unrecognized manifest key 'applications'

![image](https://user-images.githubusercontent.com/24621214/131005158-5a6fdcdd-003e-4a3d-a37e-9014f2c1346d.png)

When I delete it from manifest it works just fine as per https://stackoverflow.com/a/56823677/8719001

**Comment by cawa-93** [comment]
These fields are required to work in firefox. They should not interfere with work in chrome despite warnings.
